spring:
  cloud:
    function:
      definition: uppercase|sentence
    stream:
      bindings:
        uppercasesentence-in-0:
          destination: instrument
          group: stream-function
        uppercasesentence-out-0:
          destination: skill
