name: CI Pipeline
on: [push]

jobs:
  build-service:
    name: Web Service - Compile and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile and test
        run: |
          cd web-service
          chmod +x gradlew
          ./gradlew clean build
  build-function:
    name: Web Function - Compile and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile and test
        run: |
          cd web-function
          chmod +x gradlew
          ./gradlew clean build
  build-stream:
    name: Stream Function - Compile and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Compile and test
        run: |
          cd stream-function
          chmod +x gradlew
          ./gradlew clean build